Solve following test error with basic-layout.
Error: Template parse errors:
There is no directive with "exportAs" set to "routerLinkActive" ("
     *ngFor="let tab of tabs"
     [routerLink]="tab.link"
     routerLinkActive [ERROR ->]#rla="routerLinkActive"
     [active]="rla.isActive">
     {{tab.label}}
"): ng:///DynamicTestModule/BasicLayoutComponent.html@4:22
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
  <a md-tab-link
     *ngFor="let tab of tabs"
     [ERROR ->][routerLink]="tab.link"
     routerLinkActive #rla="routerLinkActive"
     [active]="rla.isActive">
"): ng:///DynamicTestModule/BasicLayoutComponent.html@3:5
Can't bind to 'active' since it isn't a known property of 'a'. ("
     [routerLink]="tab.link"
     routerLinkActive #rla="routerLinkActive"
     [ERROR ->][active]="rla.isActive">
     {{tab.label}}
  </a>
"): ng:///DynamicTestModule/BasicLayoutComponent.html@5:5